@startuml
'https://plantuml.com/class-diagram

class Gos {
    -- Atributs --
    - nom: String
    - especie: String
    - xip: Int
    - pes: Float
    - color: Color
    - teRabia: Boolean
    - mossega: Boolean
    - cadells: MutableList<Gos>
    -- Mètodes --
    + constructor(String): Gos
    + constructor(String,String,Int): Gos
    + constructor(String,String,Ing,Float,String,Boolean,Boolean): Gos
    + afegirCadell(Gos)
    + toString(): String
}

@enduml